### ISSUE TITLE
superscripts in blog post references now broken?

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/roweb2#132]
@marulango or @jeroen In this blog post, https://ropensci.org/blog/2017/10/06/sholler-plan/, references in the text are no longer superscripted, whereas I think they did appear superscripted when we first launched the new site.

![screen shot 2017-11-21 at 11 26 51 am](https://user-images.githubusercontent.com/11927811/33092420-f5d37636-ceae-11e7-9ac6-1ad30a0cbbb6.png)

**Comment by maelle** [comment]
Source = https://github.com/ropensci/roweb2/blob/master/content/blog/2017-10-06-sholler-plan.md

**Comment by maelle** [comment]
Notes from my reading

* https://discourse.gohugo.io/t/correct-syntax-to-display-subscript-in-markdown-content/7314/2 it says it could be a font thing but I highly doubt it is since @stefaniebutland said the superscripts used to be there.

* https://gohugobrasil.netlify.com/getting-started/configuration/#blackfriday-extensions says the `footnotes` extension is enabled by default 🤔

**Comment by maelle** [comment]
Ahah I :eyes: https://github.com/ropensci/roweb2/blob/99277fae89c91f52cee504c144d263794ea89ec9/themes/ropensci/static/css/style-new.css#L9 `sup` is in the list of these things that get `vertical-align: baseline;`
