### ISSUE TITLE
Add a bio line for all staff members

### ISSUE THREAD

**Issue by maelle** [ropensci/roweb2#375]
in the authors metadata

**Comment by stefaniebutland** [comment]
Added staff bio lines.
Decided to shorten them to e.g. rOpenSci Community Manager, rather than "Stefanie Butland is rOpenSci's Community Manager because the longer line looked awkward in blog post listing page.

Question: Do you think we can live without the comma after the twitter icon? Example: https://ropensci.org/blog/2018/12/05/commcall-dec2018/
Or would it look strange if we had a staff member without an icon?

**Comment by maelle** [comment]
Thank you!

I've just removed the bio from the authors partial (@jeroen told me about it too). I have trouble imagining how to make it look good with the bio in it. I'm sorry about that.

The bio still appears in author pages themselves.

I've added the "description" parameter to comm call single pages and in the description one can add the affiliation which I did for Jeroen's and Dan's calls. I am a bit annoyed at how `markdownify` removed white spaces in the description of Jeroen's call but that's another issue.

Is this an ok compromise?

(git push super slow but in progress)

**Comment by jeroen** [comment]
I would prefer if for blog posts, the link in the author name goes to the author's ropensci index page on ropensci, rather than an external website.

In the future we could further personalize the author's index pages with a, bio, icons to github/twitter, perhaps a photo, in addition to the list of posts.

**Comment by maelle** [comment]
Am fine with all the changes proposed if @stefaniebutland agrees. Would this index page be linked for all authors including one-time author?

I'll open an issue about the fancy author's index pages because I like that idea.
