### ISSUE TITLE
find occurrences of figures and replace them with Hugo figure shortcode

### ISSUE THREAD

**Issue by maelle** [ropensci/roweb2#663]
e.g. https://github.com/ropensci/roweb2/blob/master/content/blog/2019-06-04-rromeo.md

**Comment by maelle** [comment]
```
grep '<figure>' . -R -l
./content/blog/2019-06-04-rromeo.md
./content/blog/2017-03-21-camsrad.md
./content/blog/2019-05-14-nasapower.md
```

**Comment by stefaniebutland** [comment]
formatting of speakers bios in this community call post is messed up (because of figures?) 

live: https://ropensci.org/blog/2020/03/04/commcall-mar2020/
raw: https://raw.githubusercontent.com/ropensci/roweb2/master/content/blog/2020-03-04-commcall-mar2020/index.md

It's likely that all past commcalls blog announcments have same issue. Filenames are like `commcall-mar2020`
