### ISSUE TITLE
Post launch enhancements

### ISSUE THREAD

**Issue by karthik** [ropensci/roweb2#82]
- Need a better Jekll theme for the community calls gh-pages
- Need a better Jekyll theme for the onboarding.ropensci.org page (basically the README on the repo)
- Need a generic unconf page (unconf.ropensci.org) generated from a repo or just a page on the website.

**Comment by stefaniebutland** [comment]
💯need generic unconf page sooner rather than later. IMO ideal solution is to be a page on our website, but for now prob should create unconf.ropensci.org generated from a repo.

From Karthik Aug 2017:
- Highlights what the event is about
- How it works
- How to get involved
It could also include some generic information for sponsors. I moved the old repos (hackathon, unconf etc) to unconf14, unconf15 and along with unconf16 and unconf17, it makes for a nice series of repos.

**Comment by maelle** [comment]
Why does the comm call page need to be in a separate repo by the way? Any reason why it's not a page in this Hugo project?

**Comment by karthik** [comment]
Can't remember but Stef was having issues with keeping the html tables updated and formatted nicely iirc. So we decided to make it a separate subdomain with a simple markdown table/theme to keep that easily updated as an archive.

**Comment by maelle** [comment]
Ok, but now the table is html because I transformed it (with Stef's agreement 😸 ) to have a direct link to each call.

**Comment by stefaniebutland** [comment]
> Why does the comm call page need to be in a separate repo by the way?

I think it would be best to have comm call page as part of roweb2. 

Historically, Comm Calls started in that separate repo and I don't think we listed all past calls resources in one place - each was in one issue. I put the table of all calls in the README so Karthik could add Jekyll theme. This was a good quick fix and then @maelle you added the super-helpful anchors.

Can't think of any reason not to have community calls page in Hugo roweb2. (am I missing anything?)

**Comment by maelle** [comment]
Ok, thanks. I think we could move the commcalls to roweb2, it makes sense to have everything under one (very stylish) umbrella. It'd be a folder under content/ and would need a layout for
* each comm call page.
* the list of comm calls (happy to make it a table, I'd just need info for each comm call to live in the YAML).

We'd also need a redirect from https://communitycalls.ropensci.org/ to ropensci.org/commcalls.

We'd also need to be wise regarding the RSS feed and my makeshift archive page. The general RSS feed of the website would include blog, comm calls, tech notes I think because of the date in YAML. It's fine to have such a rich RSS (ahahah) but we need to check what had been submitted to R-bloggers.

We'd also see a given overlap between blog posts about comm calls and comm calls pages but it was already the case.

Last point, the comm calls are sort of events and would need to be included in the calendar generated through Hugo (not an issue, I just need to create that list of events wisely).

**Comment by maelle** [comment]
@sckott I think it's a very similar challenge to move the newsletter to roweb2. I'm very motivated to help with both moves. 😺

**Comment by maelle** [comment]
In each comm call page, the vimeo video could be embedded https://gohugo.io/content-management/shortcodes/ It could be done by default, each comm call .md being only YAML, and the template defining the use of the Vimeo partial.
It could be actually embedded, or via a thumbnail cf https://gohugo.io/about/hugo-and-gdpr/#vimeo

**Comment by maelle** [comment]
Closing this since there are now separate issues for the comm calls transfer (I will tackle that with the calendar, and will ping you reg the redirection when time comes @karthik), the onboarding page #332  and the unconf page #333
